Implement waitTillLastBlockProcessed helper function
coingaming/src pull request #16
Opened 2022-02-23 13:18 UTC by prushin

2022-02-23 14:04 UTC, tim2CF requested changes

2022-02-23 14:04 UTC, tim2CF commented on btc-lsp/test/RpcSpec.hs
> +  focus $
Unfocus

2022-02-23 15:24 UTC, prushin commented on btc-lsp/test/RpcSpec.hs
> +            () <- waitTillLastBlockProcessedT 100
okay

2022-02-23 15:24 UTC, prushin commented on btc-lsp/test/RpcSpec.hs
> +  focus $
done

2022-02-23 15:25 UTC, prushin commented on btc-lsp/src/BtcLsp/Rpc/Helper.hs
> +    _ -> return ()
good idea, actually if height the same there couldn't be other block
but better double check

2022-02-23 19:25 UTC, prushin commented on btc-lsp/src/BtcLsp/Rpc/Helper.hs
> +    _ -> return ()
after series of investigations looks like there is the same hash, but in some other format
so doesn't match

2022-03-02 13:23 UTC, tim2CF approved these changes
Good!

2022-03-02 13:23 UTC, merged