B1M2-5424
coingaming/src pull request #78
Opened 2022-05-11 12:24 UTC by prushin

2022-05-11 13:00 UTC, tim2CF requested changes

2022-05-11 13:23 UTC, drownbes requested changes

2022-05-11 13:23 UTC, drownbes commented on btc-lsp/src/BtcLsp/Storage/Model/Block.hs
> +                       Psql.==. Psql.val BlkConfirmed
EIther function name or block status are incorrect.  getOrphan but status is confirmed. Is that correct?

2022-05-11 13:23 UTC, drownbes commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +        then return $ Right ()
Also why returns instead of _pure_ that we used to use in repo?

2022-05-11 13:58 UTC, prushin commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +      cHash <- withBtcT Btc.getBlockHash (\h -> h height)
ok

2022-05-11 13:59 UTC, prushin commented on btc-lsp/test/ReorgSpec.hs
> +spec = focus $
ok

2022-05-13 08:17 UTC, prushin commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +        then return $ Right ()
yes, made it a bit more functional

2022-05-13 08:36 UTC, prushin commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +            blks <- Block.getOrphanBlocksHigherSql bHeight
ok

2022-05-13 08:36 UTC, prushin commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +            Block.makeOrphanBlocksHigherSql bHeight
ok

2022-05-13 08:38 UTC, prushin commented on btc-lsp/src/BtcLsp/Thread/BlockScanner.hs
> +            Block.makeOrphanBlocksHigherSql bHeight
detectReorg is actually tries to compare blocks until hashes are the same and in case of reorg returns height when hashes are equal

2022-05-13 08:42 UTC, prushin commented on btc-lsp/src/BtcLsp/Storage/Model/SwapUtxo.hs
> +          Psql.=. Psql.val SwapUtxoUsedForChanFunding,
there is also issue with statuses of blocks that can be affected by orphan block

2022-05-17 08:26 UTC, tim2CF approved these changes
Good job!

2022-05-17 09:41 UTC, merged